import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, ArrowLeft, ArrowRight, BarChart3, Bot, ChevronRight, Clock3, Gauge, HeartPulse, Menu, Search, ShieldCheck, Sparkles, Target, TrendingUp, X, Zap} from 'lucide-react';
import './styles.css';

const API = import.meta.env.VITE_API_URL || 'http://127.0.0.1:8000/api/v1';
const fallbackMatches = [
 {id:1,league:'Premier League',season:'2026/27',kickoff_time:new Date(Date.now()+28800000).toISOString(),home_team:{name:'Arsenal',country:'England',form_score:82},away_team:{name:'Chelsea',country:'England',form_score:67}},
 {id:2,league:'Club World Cup',season:'2026',kickoff_time:new Date(Date.now()+86400000).toISOString(),home_team:{name:'Barcelona',country:'Spain',form_score:86},away_team:{name:'Inter Milan',country:'Italy',form_score:79}},
 {id:3,league:'Champions League',season:'2026/27',kickoff_time:new Date(Date.now()+172800000).toISOString(),home_team:{name:'Bayern Munich',country:'Germany',form_score:84},away_team:{name:'Paris Saint-Germain',country:'France',form_score:81}},
];
const flags={England:'🏴',Spain:'🇪🇸',Italy:'🇮🇹',Germany:'🇩🇪',France:'🇫🇷'};
const initials=n=>n.split(' ').map(x=>x[0]).slice(0,2).join('');

function App(){
 const [matches,setMatches]=useState([]),[selected,setSelected]=useState(null),[prediction,setPrediction]=useState(null),[menu,setMenu]=useState(false),[route,setRoute]=useState(location.hash.slice(1)||'predictions'),[source,setSource]=useState('loading'),[provider,setProvider]=useState(null);
 useEffect(()=>{const change=()=>{setRoute(location.hash.slice(1)||'predictions');setSelected(null);setMenu(false)};addEventListener('hashchange',change);return()=>removeEventListener('hashchange',change)},[]);
 useEffect(()=>{Promise.all([fetch(`${API}/sync/status`).then(r=>r.ok?r.json():Promise.reject()),fetch(`${API}/fixtures/?days=30`).then(r=>r.ok?r.json():Promise.reject())]).then(([status,rows])=>{setProvider(status);setSource(status.configured?'football-data.org':'local demo');if(rows.length)setMatches(rows.map(m=>({...m,league:m.league.name})));else if(status.configured)setMatches([]);else throw new Error('Provider unavailable')}).catch(()=>{setProvider({configured:false,enabled:false,provider:'football-data.org'});fetch(`${API}/matches/`).then(r=>r.ok?r.json():Promise.reject()).then(async rows=>{const rich=await Promise.all(rows.map(m=>fetch(`${API}/matches/${m.id}`).then(r=>r.json())));setMatches(rich.length?rich:fallbackMatches);setSource('local demo')}).catch(()=>{setMatches(fallbackMatches);setSource('preview fallback')})})},[]);
 useEffect(()=>{if(!selected)return; setPrediction(null); fetch(`${API}/intelligence/${selected.id}`).then(r=>r.ok?r.json():Promise.reject()).then(setPrediction).catch(()=>setPrediction({error:'Analysis is unavailable because verified model inputs could not be loaded.'}))},[selected]);
 const page=selected?<Detail match={selected} p={prediction} back={()=>setSelected(null)}/>:route==='insights'?<Insights matches={matches} source={source}/>:route==='leagues'?<Leagues provider={provider}/>:route==='pricing'?<Pricing/>:<Home matches={matches} open={setSelected} source={source} provider={provider}/>;
 return <><Header menu={menu} setMenu={setMenu}/>{page}<Footer/></>
}
function fallbackReport(m){const prediction={home_win_probability:62,draw_probability:23,away_win_probability:15,confidence_score:62,risk_level:'medium',expected_home_goals:2.13,expected_away_goals:.94,reasoning:[`${m.home_team.name} carries the stronger recent form and creates more high-quality chances.`,`Home advantage and superior ball progression increase sustained pressure.`,`${m.away_team.name} remains dangerous in transition, which keeps uncertainty meaningful.`]};return {prediction,model_version:'fiq-poisson-market-1.1',data_status:'Preview data — connect licensed providers for production use',confidence:{reliability:62,model_agreement:91,historical_similarity:0,data_freshness:0,lineup_certainty:0,weather_uncertainty:'Low'},simulation:{runs:100000,home_wins:62000,draws:23000,away_wins:15000,most_common_scores:[{score:'2-1',probability:14.8},{score:'1-0',probability:12.9},{score:'2-0',probability:11.4}]},goals_markets:{over_2_5:58,btts:54,expected_corners:10.4,expected_cards:3.8},tactics:{home:{team:m.home_team.name,formation:'4-3-3',possession:61,pressing:'High',wing_attacks:'Very high',counter_attack:'Low',defensive_line:'High'},away:{team:m.away_team.name,formation:'4-2-3-1',possession:39,pressing:'Medium',wing_attacks:'High',counter_attack:'Medium',defensive_line:'Balanced'},key_battle:'Midfield control and second-ball recoveries',match_pattern:`${m.home_team.name} should control territory while ${m.away_team.name} threaten in transition.`},injuries:{home:{active:0,impact_score:0,availability:'Confirmed',explanation:'No high-impact absences are recorded.'},away:{active:2,impact_score:12,availability:'Monitor',explanation:'Two absences reduce defensive continuity and ball progression.'}},momentum:{home:{team:m.home_team.name,index:88,trend:'Improving'},away:{team:m.away_team.name,index:69,trend:'Stable'}},odds:{bookmakers:[{name:'NorthStar',home:1.72,draw:3.65,away:4.8},{name:'PrimeBet',home:1.76,draw:3.55,away:4.65}],best_home_odds:1.76,shortest_home_odds:1.72,movement:'Stable — no historical odds snapshots connected',explanation:'Market probability is normalized and blended at a controlled 30% weight.'},transparency:{published_probability:62,actual_result:null,settled:false,calibration_bucket:'60%–69%',method:'Dampened Elo/form → Poisson score model → market blend → confidence calibration'}}}
function Header({menu,setMenu}){return <header><a className="brand" href="#predictions"><span>F</span>FootballIQ</a><nav className={menu?'open':''}><a href="#predictions">Predictions</a><a href="#insights">Insights</a><a href="#leagues">Leagues</a><a href="#pricing">Pricing</a><a href="#method">How it works</a></nav><div className="header-actions"><button className="icon-btn" aria-label="Search"><Search size={19}/></button><a className="primary small" href="#pricing">Get Pro</a><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>}
function Home({matches,open,source,provider}){const [filter,setFilter]=useState('All');const shown=useMemo(()=>filter==='All'?matches:matches.filter(m=>m.league.includes(filter)),[matches,filter]);return <main>
 <section className="hero"><div className="eyebrow"><Sparkles size={15}/> Explainable football intelligence</div><h1>See the match.<br/><em>Understand the outcome.</em></h1><p>Transparent, data-led football predictions built from form, team strength, market signals and match context—so you know what drives every call.</p><div className="hero-actions"><a className="primary" href="#matches">View today’s predictions <ArrowRight size={18}/></a><a className="text-link" href="#method">How FootballIQ works <ChevronRight size={17}/></a></div><div className="trust"><span><ShieldCheck/> Explainable insights</span><span><Activity/> Live model signals</span><span><Target/> Probability, not promises</span></div></section>
 <section className="matches-section" id="matches"><ProviderNotice source={source} provider={provider}/><div className="section-head"><div><span className="kicker">Match centre</span><h2>Featured predictions</h2><p>Select a fixture to unlock the complete intelligence report.</p></div><div className="filters">{['All','World Cup','Premier','Champions'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div></div>
 <div className="match-grid">{shown.map((m,i)=><article className="match-card" key={m.id}><div className="card-top"><span>{m.league}</span><span><Clock3 size={14}/>{new Date(m.kickoff_time).toLocaleString([], {weekday:'short',hour:'2-digit',minute:'2-digit'})}</span></div><div className="teams"><Team team={m.home_team}/><div className="versus">VS</div><Team team={m.away_team}/></div><div className="signal"><span>Analysis status</span><strong>Calculated on request</strong></div><button className="report-btn" onClick={()=>open(m)}>Check our detailed prediction <ArrowRight size={17}/></button></article>)}</div>{source==='football-data.org'&&!shown.length&&<div className="empty-state fixtures-empty"><Clock3/><h2>No upcoming fixtures in the next 30 days</h2><p>The provider is connected and historical competition data is synchronized. FootballIQ will display scheduled matches when football-data.org publishes them.</p></div>}</section>
 <section className="method" id="method"><div><span className="kicker">Built for clarity</span><h2>Every prediction tells you why.</h2></div><div className="method-grid">{[[BarChart3,'Data in context','Form, strength, injuries and odds are weighted together.'],[Activity,'Probability model','Outcome likelihoods are calculated with an xG-based Poisson model.'],[Sparkles,'Plain-language reasoning','The strongest signals and uncertainty are explained clearly.']].map(([I,t,d],i)=><div key={t}><span className="number">0{i+1}</span><I/><h3>{t}</h3><p>{d}</p></div>)}</div></section></main>}
function ProviderNotice({source,provider}){const live=source==='football-data.org';return <div className={`provider-notice ${live?'live':'warning'}`}><Activity/><div><strong>{live?'Live provider fixtures':'Provider data is not active'}</strong><span>{live?'Fixtures on this page were synchronized from football-data.org.':provider?.configured?'Run fixture synchronization to replace local preview data.':'Add FOOTBALL_DATA_API_KEY to the backend .env, restart the API, then sync a competition.'}</span></div><b>{source}</b></div>}
function Insights({matches,source}){const upcoming=matches.filter(m=>new Date(m.kickoff_time)>new Date());const leagues=new Set(matches.map(m=>m.league));return <main className="page"><div className="page-hero"><span className="kicker">Intelligence overview</span><h1>Insights</h1><p>A transparent view of the football data currently available to FootballIQ.</p></div><div className="insight-cards"><Metric label="Upcoming fixtures" value={upcoming.length}/><Metric label="Competitions represented" value={leagues.size}/><Metric label="Current data source" value={source}/></div><section className="panel wide"><div className="panel-title"><div><span className="kicker">Coverage</span><h2>Fixtures by competition</h2></div><BarChart3/></div><div className="league-bars">{[...leagues].map(name=>{const count=matches.filter(m=>m.league===name).length;return <div key={name}><span>{name}</span><i><b style={{width:`${Math.max(8,count/Math.max(matches.length,1)*100)}%`}}/></i><strong>{count}</strong></div>})}</div>{!matches.length&&<p className="empty">No synchronized fixtures are available yet.</p>}</section></main>}
function Leagues({provider}){const [leagues,setLeagues]=useState([]),[loading,setLoading]=useState(true);useEffect(()=>{fetch(`${API}/leagues/`).then(r=>r.ok?r.json():Promise.reject()).then(setLeagues).catch(()=>setLeagues([])).finally(()=>setLoading(false))},[]);return <main className="page"><div className="page-hero"><span className="kicker">Competition coverage</span><h1>Leagues</h1><p>Competitions synchronized from football-data.org, including season and fixture coverage.</p></div>{!provider?.configured&&<ProviderNotice source="not configured" provider={provider}/>}<div className="league-grid">{leagues.map(l=><article className="league-card" key={l.id}>{l.emblem_url?<img src={l.emblem_url} alt=""/>:<div className="crest">{l.code||initials(l.name)}</div>}<div><span>{l.country||'International'}</span><h2>{l.name}</h2><p>{l.current_season||'Season unavailable'}</p></div><div className="league-stats"><Metric label="Teams" value={l.team_count}/><Metric label="Fixtures" value={l.match_count}/></div></article>)}</div>{!loading&&!leagues.length&&<div className="empty-state"><Activity/><h2>No provider leagues yet</h2><p>Configure the API key and synchronize a competition such as PL, PD, BL1, SA or FL1.</p><code>POST /api/v1/sync/competitions/PL</code></div>}</main>}
function Pricing(){const plans=[['Explorer','Free','Upcoming fixtures','Core probabilities','Transparent model notes'],['Pro','₦7,500 / month','All model markets','Fair odds and corner signals','Saved matches and alerts'],['Analyst','₦35,000 / month','Everything in Pro','CSV/API access','League and model performance']];return <main className="page pricing-page"><div className="page-hero"><span className="kicker">Football intelligence plans</span><h1>Turn match data into an edge.</h1><p>Start free. Upgrade for deeper model markets, alerts and professional analysis. Prices are launch targets; billing will activate after accounts and payments are connected.</p></div><div className="pricing-grid">{plans.map((plan,i)=><article className={`price-card ${i===1?'featured':''}`} key={plan[0]}>{i===1&&<b className="plan-badge">Most popular</b>}<span>{plan[0]}</span><h2>{plan[1]}</h2><ul>{plan.slice(2).map(item=><li key={item}><ShieldCheck/>{item}</li>)}</ul><a className={i===1?'primary':'report-btn'} href={i===0?'#predictions':'mailto:hello@footballiq.app?subject=FootballIQ founding access'}>{i===0?'Start free':'Join founding access'}</a></article>)}</div><div className="data-warning"><ShieldCheck/> FootballIQ sells explainable analytics—not guaranteed outcomes. Bookmaker feeds, payments, accounts and alerts must be licensed and production-hardened before paid launch.</div></main>}
function Team({team}){return <div className="team"><div className="crest">{team.crest_url?<img src={team.crest_url} alt={`${team.name} crest`} onError={e=>{e.currentTarget.parentElement.textContent=initials(team.name)}}/>:initials(team.name)}</div><span>{flags[team.country]||'⚽'} {team.country}</span><strong>{team.name}</strong><div className="form">{[1,1,1,0,1].map((w,i)=><i className={w?'win':'draw'} key={i}>{w?'W':'D'}</i>)}</div></div>}
function Detail({match,p:report,back}){const [tab,setTab]=useState('Overview');if(!report)return <main className="loading"><Activity/> Building your intelligence report…</main>;if(report.error)return <main className="loading">{report.error}</main>;const p=report.prediction,home=p.home_win_probability,draw=p.draw_probability,away=p.away_win_probability;const tabs=['Overview','Simulation','Tactics','Injuries & odds','Transparency'];return <main className="detail"><button className="back" onClick={back}><ArrowLeft/> Back to predictions</button><section className="match-hero"><div className="report-status"><span className="league-pill">{match.league} · {match.season}</span><span><ShieldCheck/> Model {report.model_version}</span></div><div className="detail-teams"><Team team={match.home_team}/><div className="kickoff"><strong>{new Date(match.kickoff_time).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</strong><span>{new Date(match.kickoff_time).toLocaleDateString([], {weekday:'long',month:'long',day:'numeric'})}</span><i>VS</i></div><Team team={match.away_team}/></div><div className="verdict"><span>FootballIQ verdict</span><h1>{home>away?`${match.home_team.name} have the edge`:`${match.away_team.name} have the edge`}</h1><p>{p.confidence_score}% model confidence · {p.risk_level} risk · 100,000 model simulations</p></div></section><div className="report-tabs">{tabs.map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</div>
 {tab==='Overview'&&<section className="intel-grid"><Panel icon={BarChart3} kicker="Outcome model" title="Win probability"><div className="prob-bars">{[[match.home_team.name,home,'home'],['Draw',draw,'draw'],[match.away_team.name,away,'away']].map(([n,v,c])=><div key={n}><div><span>{n}</span><strong>{v}%</strong></div><i><b className={c} style={{width:`${v}%`}}/></i></div>)}</div><p className="note">These are FootballIQ model probabilities, not bookmaker prices.</p></Panel><Panel icon={Target} kicker="Chance quality" title="Expected goals"><div className="xg-score"><div><span>{match.home_team.name}</span><strong>{p.expected_home_goals}</strong></div><i>xG</i><div><span>{match.away_team.name}</span><strong>{p.expected_away_goals}</strong></div></div><div className="metric-row"><Metric label="BTTS yes" value={`${report.goals_markets.btts}%`}/><Metric label="Over 2.5" value={`${report.goals_markets.over_2_5}%`}/><Metric label="Corners over 8.5" value={`${report.goals_markets.corners_over_8_5}%`}/></div><p className="note">{report.goals_markets.corner_model_status}</p></Panel><Panel icon={Sparkles} kicker="Explainable AI" title="Why this prediction?" wide><ol className="reason-list">{p.reasoning.map((r,i)=><li key={r}><span>{i+1}</span><p>{r}</p></li>)}</ol></Panel><Panel icon={Gauge} kicker="Confidence engine" title={`${p.confidence_score}% model confidence`}><ScoreRows data={report.confidence}/></Panel></section>}
 {tab==='Simulation'&&<section className="intel-grid"><Panel icon={Zap} kicker="Monte Carlo view" title="100,000 simulations" wide><div className="sim-results"><Metric label={`${match.home_team.name} wins`} value={report.simulation.home_wins.toLocaleString()}/><Metric label="Draws" value={report.simulation.draws.toLocaleString()}/><Metric label={`${match.away_team.name} wins`} value={report.simulation.away_wins.toLocaleString()}/></div><h3 className="subhead">Most common scorelines</h3><div className="score-chips">{report.simulation.most_common_scores.map(s=><span key={s.score}><strong>{s.score}</strong>{s.probability}%</span>)}</div></Panel><Panel icon={TrendingUp} kicker="Momentum engine" title="Form trajectory"><Momentum item={report.momentum.home}/><Momentum item={report.momentum.away}/></Panel></section>}
 {tab==='Tactics'&&<section className="intel-grid"><Tactical team={report.tactics.home}/><Tactical team={report.tactics.away}/><Panel icon={Bot} kicker="Match pattern" title="What to expect" wide><p className="lead-copy">{report.tactics.match_pattern}</p><div className="key-battle"><strong>Key battle</strong><span>{report.tactics.key_battle}</span></div></Panel></section>}
 {tab==='Injuries & odds'&&<section className="intel-grid"><Injury team={match.home_team.name} item={report.injuries.home}/><Injury team={match.away_team.name} item={report.injuries.away}/><ModelMarkets rows={report.model_markets}/><Panel icon={TrendingUp} kicker="Licensed bookmaker feed" title="Bookmaker comparison" wide><div className="odds-table"><div><strong>Bookmaker</strong><strong>Home</strong><strong>Draw</strong><strong>Away</strong></div>{report.odds.bookmakers.map(o=><div key={o.name}><span>{o.name}</span><b>{o.home}</b><b>{o.draw}</b><b>{o.away}</b></div>)}</div><p className="note">{report.odds.explanation} Live bookmaker prices require a separately licensed odds provider.</p></Panel></section>}
 {tab==='Transparency'&&<section className="intel-grid"><Panel icon={ShieldCheck} kicker="Prediction record" title="Transparent by design" wide><div className="transparency"><Metric label="Published probability" value={`${report.transparency.published_probability}%`}/><Metric label="Calibration bucket" value={report.transparency.calibration_bucket}/><Metric label="Actual result" value={report.transparency.settled?report.transparency.actual_result:'Pending'}/><Metric label="Model version" value={report.model_version}/></div><h3 className="subhead">How this was calculated</h3><p className="lead-copy">{report.transparency.method}</p><div className="data-warning"><ShieldCheck/> {report.data_status}</div></Panel></section>}<div className="disclaimer"><ShieldCheck/> Probabilities communicate uncertainty; they are information, never a guarantee or financial advice.</div></main>}
function Panel({icon:Icon,kicker,title,children,wide=false}){return <article className={`panel ${wide?'wide':''}`}><div className="panel-title"><div><span className="kicker">{kicker}</span><h2>{title}</h2></div><Icon/></div>{children}</article>}
function Metric({label,value}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>}
function ModelMarkets({rows}){return <Panel icon={TrendingUp} kicker="FootballIQ fair prices" title="Model markets" wide><div className="model-market-table"><div><strong>Market</strong><strong>Selection</strong><strong>Probability</strong><strong>Fair odds</strong><strong>Basis</strong></div>{rows.map((row,i)=><div key={`${row.market}-${row.selection}-${i}`}><span>{row.market}</span><b>{row.selection}</b><b>{row.probability}%</b><b>{row.fair_odds}</b><small className={row.basis.includes('proxy')?'proxy':''}>{row.basis}</small></div>)}</div><p className="note">Fair odds are 1 ÷ model probability with no bookmaker margin. They are reference prices, not available betting offers.</p></Panel>}
function ScoreRows({data}){return <div className="score-rows">{[['Model agreement',data.model_agreement],['Historical similarity',data.historical_similarity],['Data freshness',data.data_freshness],['Lineup certainty',data.lineup_certainty]].map(([n,v])=><div key={n}><span>{n}</span><i><b style={{width:`${v}%`}}/></i><strong>{v}%</strong></div>)}</div>}
function Momentum({item}){return <div className="momentum"><div><strong>{item.team}</strong><span>{item.trend}</span></div><b>{item.index}<small>/100</small></b><i><span style={{width:`${item.index}%`}}/></i></div>}
function Tactical({team}){return <Panel icon={Activity} kicker="Tactical AI" title={team.team}><div className="outlook">{Object.entries(team).filter(([k])=>!['team'].includes(k)).map(([k,v])=><div key={k}><span>{k.replaceAll('_',' ')}</span><strong>{k==='possession'?`${v}%`:v}</strong></div>)}</div></Panel>}
function Injury({team,item}){return <Panel icon={HeartPulse} kicker="Injury intelligence" title={team}><div className="injury-impact"><strong>{item.impact_score}</strong><span>Impact score</span></div><div className="outlook"><div><span>Active absences</span><strong>{item.active}</strong></div><div><span>Lineup status</span><strong>{item.availability}</strong></div></div><p className="note">{item.explanation}</p></Panel>}
function Footer(){return <footer><div className="brand"><span>F</span>FootballIQ</div><p>Smarter football analysis. Clearly explained.</p><small>© 2026 FootballIQ · Predictions are informational and not financial advice.</small></footer>}
createRoot(document.getElementById('root')).render(<App/>);
