import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, ArrowLeft, ArrowRight, BarChart3, Bot, ChevronRight, Clock3, Gauge, HeartPulse, Menu, Search, ShieldCheck, Sparkles, Target, TrendingUp, X, Zap} from 'lucide-react';
import './styles.css';

const API = import.meta.env.VITE_API_URL || 'http://127.0.0.1:8000/api/v1';
const fallbackMatches = [
 {id:1,league:'Premier League',season:'2026/27',kickoff_time:new Date(Date.now()+28800000).toISOString(),home_team:{name:'Arsenal',country:'England',form_score:82},away_team:{name:'Chelsea',country:'England',form_score:67}},
 {id:2,league:'Club World Cup',season:'2026',kickoff_time:new Date(Date.now()+86400000).toISOString(),home_team:{name:'Barcelona',country:'Spain',form_score:86},away_team:{name:'Inter Milan',country:'Italy',form_score:79}},
 {id:3,league:'Champions League',season:'2026/27',kickoff_time:new Date(Date.now()+172800000).toISOString(),home_team:{name:'Bayern Munich',country:'Germany',form_score:84},away_team:{name:'Paris Saint-Germain',country:'France',form_score:81}},
];
const flags={England:'🏴',Spain:'🇪🇸',Italy:'🇮🇹',Germany:'🇩🇪',France:'🇫🇷'};
const initials=n=>n.split(' ').map(x=>x[0]).slice(0,2).join('');

function App(){
 const [matches,setMatches]=useState(fallbackMatches),[selected,setSelected]=useState(null),[prediction,setPrediction]=useState(null),[menu,setMenu]=useState(false);
 useEffect(()=>{fetch(`${API}/fixtures/?days=30`).then(r=>r.ok?r.json():Promise.reject()).then(rows=>{if(!rows.length)throw new Error('No synchronized fixtures');return rows.map(m=>({...m,league:m.league.name}))}).then(setMatches).catch(()=>fetch(`${API}/matches/`).then(r=>r.ok?r.json():Promise.reject()).then(async rows=>{const rich=await Promise.all(rows.map(m=>fetch(`${API}/matches/${m.id}`).then(r=>r.json())));setMatches(rich)}).catch(()=>{}))},[]);
 useEffect(()=>{if(!selected)return; setPrediction(null); fetch(`${API}/intelligence/${selected.id}`).then(r=>r.ok?r.json():Promise.reject()).then(setPrediction).catch(()=>setPrediction(fallbackReport(selected)))},[selected]);
 return <><Header menu={menu} setMenu={setMenu}/>{selected?<Detail match={selected} p={prediction} back={()=>setSelected(null)}/>:<Home matches={matches} open={setSelected}/>}<Footer/></>
}
function fallbackReport(m){const prediction={home_win_probability:62,draw_probability:23,away_win_probability:15,confidence_score:62,risk_level:'medium',expected_home_goals:2.13,expected_away_goals:.94,reasoning:[`${m.home_team.name} carries the stronger recent form and creates more high-quality chances.`,`Home advantage and superior ball progression increase sustained pressure.`,`${m.away_team.name} remains dangerous in transition, which keeps uncertainty meaningful.`]};return {prediction,model_version:'fiq-poisson-market-1.1',data_status:'Preview data — connect licensed providers for production use',confidence:{reliability:87,model_agreement:91,historical_similarity:84,data_freshness:96,lineup_certainty:89,weather_uncertainty:'Low'},simulation:{runs:100000,home_wins:62000,draws:23000,away_wins:15000,most_common_scores:[{score:'2-1',probability:14.8},{score:'1-0',probability:12.9},{score:'2-0',probability:11.4}]},goals_markets:{over_2_5:58,btts:54,expected_corners:10.4,expected_cards:3.8},tactics:{home:{team:m.home_team.name,formation:'4-3-3',possession:61,pressing:'High',wing_attacks:'Very high',counter_attack:'Low',defensive_line:'High'},away:{team:m.away_team.name,formation:'4-2-3-1',possession:39,pressing:'Medium',wing_attacks:'High',counter_attack:'Medium',defensive_line:'Balanced'},key_battle:'Midfield control and second-ball recoveries',match_pattern:`${m.home_team.name} should control territory while ${m.away_team.name} threaten in transition.`},injuries:{home:{active:0,impact_score:0,availability:'Confirmed',explanation:'No high-impact absences are recorded.'},away:{active:2,impact_score:12,availability:'Monitor',explanation:'Two absences reduce defensive continuity and ball progression.'}},momentum:{home:{team:m.home_team.name,index:88,trend:'Improving'},away:{team:m.away_team.name,index:69,trend:'Stable'}},odds:{bookmakers:[{name:'NorthStar',home:1.72,draw:3.65,away:4.8},{name:'PrimeBet',home:1.76,draw:3.55,away:4.65}],best_home_odds:1.76,shortest_home_odds:1.72,movement:'Stable — no historical odds snapshots connected',explanation:'Market probability is normalized and blended at a controlled 30% weight.'},transparency:{published_probability:62,actual_result:null,settled:false,calibration_bucket:'60%–69%',method:'Dampened Elo/form → Poisson score model → market blend → confidence calibration'}}}
function Header({menu,setMenu}){return <header><a className="brand" href="#"><span>F</span>FootballIQ</a><nav className={menu?'open':''}><a href="#matches">Predictions</a><a href="#insights">Insights</a><a href="#leagues">Leagues</a><a href="#method">How it works</a></nav><div className="header-actions"><button className="icon-btn" aria-label="Search"><Search size={19}/></button><button className="primary small">Explore matches</button><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>}
function Home({matches,open}){const [filter,setFilter]=useState('All');const shown=useMemo(()=>filter==='All'?matches:matches.filter(m=>m.league.includes(filter)),[matches,filter]);return <main>
 <section className="hero"><div className="eyebrow"><Sparkles size={15}/> Explainable football intelligence</div><h1>See the match.<br/><em>Understand the outcome.</em></h1><p>Transparent, data-led football predictions built from form, team strength, market signals and match context—so you know what drives every call.</p><div className="hero-actions"><a className="primary" href="#matches">View today’s predictions <ArrowRight size={18}/></a><a className="text-link" href="#method">How FootballIQ works <ChevronRight size={17}/></a></div><div className="trust"><span><ShieldCheck/> Explainable insights</span><span><Activity/> Live model signals</span><span><Target/> Probability, not promises</span></div></section>
 <section className="matches-section" id="matches"><div className="section-head"><div><span className="kicker">Match centre</span><h2>Featured predictions</h2><p>Select a fixture to unlock the complete intelligence report.</p></div><div className="filters">{['All','Premier','Champions'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div></div>
 <div className="match-grid">{shown.map((m,i)=><article className="match-card" key={m.id}><div className="card-top"><span>{m.league}</span><span><Clock3 size={14}/>{new Date(m.kickoff_time).toLocaleString([], {weekday:'short',hour:'2-digit',minute:'2-digit'})}</span></div><div className="teams"><Team team={m.home_team}/><div className="versus">VS</div><Team team={m.away_team}/></div><div className="signal"><span>Model signal</span><strong>{i===1?'Balanced matchup':'Home edge detected'}</strong></div><button className="report-btn" onClick={()=>open(m)}>Check our detailed prediction <ArrowRight size={17}/></button></article>)}</div></section>
 <section className="method" id="method"><div><span className="kicker">Built for clarity</span><h2>Every prediction tells you why.</h2></div><div className="method-grid">{[[BarChart3,'Data in context','Form, strength, injuries and odds are weighted together.'],[Activity,'Probability model','Outcome likelihoods are calculated with an xG-based Poisson model.'],[Sparkles,'Plain-language reasoning','The strongest signals and uncertainty are explained clearly.']].map(([I,t,d],i)=><div key={t}><span className="number">0{i+1}</span><I/><h3>{t}</h3><p>{d}</p></div>)}</div></section></main>}
function Team({team}){return <div className="team"><div className="crest">{initials(team.name)}</div><span>{flags[team.country]||'⚽'} {team.country}</span><strong>{team.name}</strong><div className="form">{[1,1,1,0,1].map((w,i)=><i className={w?'win':'draw'} key={i}>{w?'W':'D'}</i>)}</div></div>}
function Detail({match,p:report,back}){const [tab,setTab]=useState('Overview');if(!report)return <main className="loading"><Activity/> Building your intelligence report…</main>;const p=report.prediction,home=p.home_win_probability,draw=p.draw_probability,away=p.away_win_probability;const tabs=['Overview','Simulation','Tactics','Injuries & odds','Transparency'];return <main className="detail"><button className="back" onClick={back}><ArrowLeft/> Back to predictions</button><section className="match-hero"><div className="report-status"><span className="league-pill">{match.league} · {match.season}</span><span><ShieldCheck/> Model {report.model_version}</span></div><div className="detail-teams"><Team team={match.home_team}/><div className="kickoff"><strong>{new Date(match.kickoff_time).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</strong><span>{new Date(match.kickoff_time).toLocaleDateString([], {weekday:'long',month:'long',day:'numeric'})}</span><i>VS</i></div><Team team={match.away_team}/></div><div className="verdict"><span>FootballIQ verdict</span><h1>{home>away?`${match.home_team.name} have the edge`:`${match.away_team.name} have the edge`}</h1><p>{report.confidence.reliability}% reliability · {p.risk_level} risk · 100,000 model simulations</p></div></section><div className="report-tabs">{tabs.map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</div>
 {tab==='Overview'&&<section className="intel-grid"><Panel icon={BarChart3} kicker="Outcome model" title="Win probability"><div className="prob-bars">{[[match.home_team.name,home,'home'],['Draw',draw,'draw'],[match.away_team.name,away,'away']].map(([n,v,c])=><div key={n}><div><span>{n}</span><strong>{v}%</strong></div><i><b className={c} style={{width:`${v}%`}}/></i></div>)}</div><p className="note">Margin-free market probabilities are blended with the independent model.</p></Panel><Panel icon={Target} kicker="Chance quality" title="Expected goals"><div className="xg-score"><div><span>{match.home_team.name}</span><strong>{p.expected_home_goals}</strong></div><i>xG</i><div><span>{match.away_team.name}</span><strong>{p.expected_away_goals}</strong></div></div><div className="metric-row"><Metric label="BTTS" value={`${report.goals_markets.btts}%`}/><Metric label="Over 2.5" value={`${report.goals_markets.over_2_5}%`}/><Metric label="Corners" value={report.goals_markets.expected_corners}/></div></Panel><Panel icon={Sparkles} kicker="Explainable AI" title="Why this prediction?" wide><ol className="reason-list">{p.reasoning.map((r,i)=><li key={r}><span>{i+1}</span><p>{r}</p></li>)}</ol></Panel><Panel icon={Gauge} kicker="Confidence engine" title={`${report.confidence.reliability}% reliability`}><ScoreRows data={report.confidence}/></Panel></section>}
 {tab==='Simulation'&&<section className="intel-grid"><Panel icon={Zap} kicker="Monte Carlo view" title="100,000 simulations" wide><div className="sim-results"><Metric label={`${match.home_team.name} wins`} value={report.simulation.home_wins.toLocaleString()}/><Metric label="Draws" value={report.simulation.draws.toLocaleString()}/><Metric label={`${match.away_team.name} wins`} value={report.simulation.away_wins.toLocaleString()}/></div><h3 className="subhead">Most common scorelines</h3><div className="score-chips">{report.simulation.most_common_scores.map(s=><span key={s.score}><strong>{s.score}</strong>{s.probability}%</span>)}</div></Panel><Panel icon={TrendingUp} kicker="Momentum engine" title="Form trajectory"><Momentum item={report.momentum.home}/><Momentum item={report.momentum.away}/></Panel></section>}
 {tab==='Tactics'&&<section className="intel-grid"><Tactical team={report.tactics.home}/><Tactical team={report.tactics.away}/><Panel icon={Bot} kicker="Match pattern" title="What to expect" wide><p className="lead-copy">{report.tactics.match_pattern}</p><div className="key-battle"><strong>Key battle</strong><span>{report.tactics.key_battle}</span></div></Panel></section>}
 {tab==='Injuries & odds'&&<section className="intel-grid"><Injury team={match.home_team.name} item={report.injuries.home}/><Injury team={match.away_team.name} item={report.injuries.away}/><Panel icon={TrendingUp} kicker="Odds intelligence" title="Market comparison" wide><div className="odds-table"><div><strong>Bookmaker</strong><strong>Home</strong><strong>Draw</strong><strong>Away</strong></div>{report.odds.bookmakers.map(o=><div key={o.name}><span>{o.name}</span><b>{o.home}</b><b>{o.draw}</b><b>{o.away}</b></div>)}</div><p className="note">{report.odds.explanation} {report.odds.movement}</p></Panel></section>}
 {tab==='Transparency'&&<section className="intel-grid"><Panel icon={ShieldCheck} kicker="Prediction record" title="Transparent by design" wide><div className="transparency"><Metric label="Published probability" value={`${report.transparency.published_probability}%`}/><Metric label="Calibration bucket" value={report.transparency.calibration_bucket}/><Metric label="Actual result" value={report.transparency.settled?report.transparency.actual_result:'Pending'}/><Metric label="Model version" value={report.model_version}/></div><h3 className="subhead">How this was calculated</h3><p className="lead-copy">{report.transparency.method}</p><div className="data-warning"><ShieldCheck/> {report.data_status}</div></Panel></section>}<div className="disclaimer"><ShieldCheck/> Probabilities communicate uncertainty; they are information, never a guarantee or financial advice.</div></main>}
function Panel({icon:Icon,kicker,title,children,wide=false}){return <article className={`panel ${wide?'wide':''}`}><div className="panel-title"><div><span className="kicker">{kicker}</span><h2>{title}</h2></div><Icon/></div>{children}</article>}
function Metric({label,value}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>}
function ScoreRows({data}){return <div className="score-rows">{[['Model agreement',data.model_agreement],['Historical similarity',data.historical_similarity],['Data freshness',data.data_freshness],['Lineup certainty',data.lineup_certainty]].map(([n,v])=><div key={n}><span>{n}</span><i><b style={{width:`${v}%`}}/></i><strong>{v}%</strong></div>)}</div>}
function Momentum({item}){return <div className="momentum"><div><strong>{item.team}</strong><span>{item.trend}</span></div><b>{item.index}<small>/100</small></b><i><span style={{width:`${item.index}%`}}/></i></div>}
function Tactical({team}){return <Panel icon={Activity} kicker="Tactical AI" title={team.team}><div className="outlook">{Object.entries(team).filter(([k])=>!['team'].includes(k)).map(([k,v])=><div key={k}><span>{k.replaceAll('_',' ')}</span><strong>{k==='possession'?`${v}%`:v}</strong></div>)}</div></Panel>}
function Injury({team,item}){return <Panel icon={HeartPulse} kicker="Injury intelligence" title={team}><div className="injury-impact"><strong>{item.impact_score}</strong><span>Impact score</span></div><div className="outlook"><div><span>Active absences</span><strong>{item.active}</strong></div><div><span>Lineup status</span><strong>{item.availability}</strong></div></div><p className="note">{item.explanation}</p></Panel>}
function Footer(){return <footer><div className="brand"><span>F</span>FootballIQ</div><p>Smarter football analysis. Clearly explained.</p><small>© 2026 FootballIQ · Predictions are informational and not financial advice.</small></footer>}
createRoot(document.getElementById('root')).render(<App/>);
