import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, ArrowLeft, ArrowRight, BarChart3, CalendarDays, ChevronRight, CircleDot, Clock3, Menu, Search, ShieldCheck, Sparkles, Target, TrendingUp, X} from 'lucide-react';
import './styles.css';

const API = import.meta.env.VITE_API_URL || 'http://127.0.0.1:8000/api/v1';
const fallbackMatches = [
 {id:1,league:'Premier League',season:'2026/27',kickoff_time:new Date(Date.now()+28800000).toISOString(),home_team:{name:'Arsenal',country:'England',form_score:82},away_team:{name:'Chelsea',country:'England',form_score:67}},
 {id:2,league:'Club World Cup',season:'2026',kickoff_time:new Date(Date.now()+86400000).toISOString(),home_team:{name:'Barcelona',country:'Spain',form_score:86},away_team:{name:'Inter Milan',country:'Italy',form_score:79}},
 {id:3,league:'Champions League',season:'2026/27',kickoff_time:new Date(Date.now()+172800000).toISOString(),home_team:{name:'Bayern Munich',country:'Germany',form_score:84},away_team:{name:'Paris Saint-Germain',country:'France',form_score:81}},
];
const flags={England:'🏴',Spain:'🇪🇸',Italy:'🇮🇹',Germany:'🇩🇪',France:'🇫🇷'};
const initials=n=>n.split(' ').map(x=>x[0]).slice(0,2).join('');

function App(){
 const [matches,setMatches]=useState(fallbackMatches),[selected,setSelected]=useState(null),[prediction,setPrediction]=useState(null),[menu,setMenu]=useState(false);
 useEffect(()=>{fetch(`${API}/matches/`).then(r=>r.ok?r.json():Promise.reject()).then(async rows=>{const rich=await Promise.all(rows.map(m=>fetch(`${API}/matches/${m.id}`).then(r=>r.json())));setMatches(rich)}).catch(()=>{})},[]);
 useEffect(()=>{if(!selected)return; setPrediction(null); fetch(`${API}/predictions/${selected.id}`).then(r=>r.ok?r.json():Promise.reject()).then(setPrediction).catch(()=>setPrediction({home_win_probability:62,draw_probability:23,away_win_probability:15,confidence_score:62,risk_level:'medium',expected_home_goals:2.13,expected_away_goals:.94,reasoning:[`${selected.home_team.name} carries the stronger recent form and creates more high-quality chances.`,`Home advantage and superior ball progression increase sustained pressure.`,`The away side remains dangerous in transition, which keeps uncertainty meaningful.`]}))},[selected]);
 return <><Header menu={menu} setMenu={setMenu}/>{selected?<Detail match={selected} p={prediction} back={()=>setSelected(null)}/>:<Home matches={matches} open={setSelected}/>}<Footer/></>
}
function Header({menu,setMenu}){return <header><a className="brand" href="#"><span>F</span>FootballIQ</a><nav className={menu?'open':''}><a href="#matches">Predictions</a><a href="#insights">Insights</a><a href="#leagues">Leagues</a><a href="#method">How it works</a></nav><div className="header-actions"><button className="icon-btn" aria-label="Search"><Search size={19}/></button><button className="primary small">Explore matches</button><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>}
function Home({matches,open}){const [filter,setFilter]=useState('All');const shown=useMemo(()=>filter==='All'?matches:matches.filter(m=>m.league.includes(filter)),[matches,filter]);return <main>
 <section className="hero"><div className="eyebrow"><Sparkles size={15}/> Explainable football intelligence</div><h1>See the match.<br/><em>Understand the outcome.</em></h1><p>Transparent, data-led football predictions built from form, team strength, market signals and match context—so you know what drives every call.</p><div className="hero-actions"><a className="primary" href="#matches">View today’s predictions <ArrowRight size={18}/></a><a className="text-link" href="#method">How FootballIQ works <ChevronRight size={17}/></a></div><div className="trust"><span><ShieldCheck/> Explainable insights</span><span><Activity/> Live model signals</span><span><Target/> Probability, not promises</span></div></section>
 <section className="matches-section" id="matches"><div className="section-head"><div><span className="kicker">Match centre</span><h2>Featured predictions</h2><p>Select a fixture to unlock the complete intelligence report.</p></div><div className="filters">{['All','Premier','Champions'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div></div>
 <div className="match-grid">{shown.map((m,i)=><article className="match-card" key={m.id}><div className="card-top"><span>{m.league}</span><span><Clock3 size={14}/>{new Date(m.kickoff_time).toLocaleString([], {weekday:'short',hour:'2-digit',minute:'2-digit'})}</span></div><div className="teams"><Team team={m.home_team}/><div className="versus">VS</div><Team team={m.away_team}/></div><div className="signal"><span>Model signal</span><strong>{i===1?'Balanced matchup':'Home edge detected'}</strong></div><button className="report-btn" onClick={()=>open(m)}>Check our detailed prediction <ArrowRight size={17}/></button></article>)}</div></section>
 <section className="method" id="method"><div><span className="kicker">Built for clarity</span><h2>Every prediction tells you why.</h2></div><div className="method-grid">{[[BarChart3,'Data in context','Form, strength, injuries and odds are weighted together.'],[Activity,'Probability model','Outcome likelihoods are calculated with an xG-based Poisson model.'],[Sparkles,'Plain-language reasoning','The strongest signals and uncertainty are explained clearly.']].map(([I,t,d],i)=><div key={t}><span className="number">0{i+1}</span><I/><h3>{t}</h3><p>{d}</p></div>)}</div></section></main>}
function Team({team}){return <div className="team"><div className="crest">{initials(team.name)}</div><span>{flags[team.country]||'⚽'} {team.country}</span><strong>{team.name}</strong><div className="form">{[1,1,1,0,1].map((w,i)=><i className={w?'win':'draw'} key={i}>{w?'W':'D'}</i>)}</div></div>}
function Detail({match,p,back}){if(!p)return <main className="loading"><Activity/> Analysing the match…</main>;const home=p.home_win_probability,draw=p.draw_probability,away=p.away_win_probability;return <main className="detail"><button className="back" onClick={back}><ArrowLeft/> Back to predictions</button><section className="match-hero"><span className="league-pill">{match.league} · {match.season}</span><div className="detail-teams"><Team team={match.home_team}/><div className="kickoff"><strong>{new Date(match.kickoff_time).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</strong><span>{new Date(match.kickoff_time).toLocaleDateString([], {weekday:'long',month:'long',day:'numeric'})}</span><i>VS</i></div><Team team={match.away_team}/></div><div className="verdict"><span>FootballIQ verdict</span><h1>{home>away?`${match.home_team.name} have the edge`:`${match.away_team.name} have the edge`}</h1><p>Confidence {p.confidence_score}% · {p.risk_level} conviction</p></div></section>
 <section className="intel-grid"><article className="panel probability"><div className="panel-title"><div><span className="kicker">Outcome model</span><h2>Win probability</h2></div><BarChart3/></div><div className="prob-bars">{[[match.home_team.name,home,'home'],['Draw',draw,'draw'],[match.away_team.name,away,'away']].map(([n,v,c])=><div><div><span>{n}</span><strong>{v}%</strong></div><i><b className={c} style={{width:`${v}%`}}/></i></div>)}</div><p className="note">Probabilities are normalized from the model and current market signal.</p></article>
 <article className="panel xg"><div className="panel-title"><div><span className="kicker">Chance quality</span><h2>Expected goals</h2></div><Target/></div><div className="xg-score"><div><span>{match.home_team.name}</span><strong>{p.expected_home_goals}</strong></div><i>xG</i><div><span>{match.away_team.name}</span><strong>{p.expected_away_goals}</strong></div></div><div className="total"><span>Projected goal environment</span><strong>{p.expected_home_goals+p.expected_away_goals>=2.5?'Open / attacking':'Controlled / lower scoring'}</strong></div></article>
 <article className="panel reasoning"><div className="panel-title"><div><span className="kicker">Model explanation</span><h2>Why this prediction?</h2></div><Sparkles/></div><ol>{p.reasoning.map((r,i)=><li key={`${i}-${r}`}><span>{i+1}</span><p>{r}</p></li>)}</ol></article>
 <article className="panel markets"><div className="panel-title"><div><span className="kicker">Decision support</span><h2>Match outlook</h2></div><TrendingUp/></div><div className="outlook"><div><span>Most likely result</span><strong>{home>away?'Home win':'Away win'}</strong></div><div><span>Both teams to score</span><strong>{p.expected_away_goals>.8?'Possible':'Less likely'}</strong></div><div><span>Over 2.5 goals</span><strong>{p.expected_home_goals+p.expected_away_goals>2.5?'Lean yes':'Lean no'}</strong></div><div><span>Risk rating</span><strong className={p.risk_level}>{p.risk_level}</strong></div></div><div className="disclaimer"><ShieldCheck/> Use these probabilities as information, not certainty. Football remains unpredictable.</div></article></section></main>}
function Footer(){return <footer><div className="brand"><span>F</span>FootballIQ</div><p>Smarter football analysis. Clearly explained.</p><small>© 2026 FootballIQ · Predictions are informational and not financial advice.</small></footer>}
createRoot(document.getElementById('root')).render(<App/>);
